language: php

php:
  - 7.1
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - LARAVEL_VERSION="5.4.*" ORCHESTRA_VERSION="^3.4.2" COMPOSER_FLAGS="--prefer-lowest"
    - LARAVEL_VERSION="5.4.*" ORCHESTRA_VERSION="^3.4.2" COMPOSER_FLAGS="--prefer-stable"
    - LARAVEL_VERSION="dev-master" ORCHESTRA_VERSION="dev-master"

matrix:
  allow_failures:
    - php: nightly
    - env: ILLUMINATE_VERSION="dev-master" ORCHESTRA_VERSION="dev-master"
  fast_finish: true

before_install:
  - travis_retry composer self-update
  - composer require laravel/framework=${LARAVEL_VERSION} --no-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit

branches:
  only:
    - master
    - develop

notifications:
  email:
    on_failure: change
    on_success: never
